"""add sample answers table

Revision ID: 1d95652f9f96
Revises: 7fbe49827ed0
Create Date: 2025-06-28 23:11:17.196861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d95652f9f96'
down_revision = '7fbe49827ed0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_index(op.f('ix_sample_answers_id'), 'sample_answers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sample_answers_id'), table_name='sample_answers')
    op.drop_table('sample_answers')
    # ### end Alembic commands ### 