"""update difficulty enum values

Revision ID: 631a0811a631
Revises: fcbc32ac6fdd
Create Date: 2025-06-28 23:56:53.772061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '631a0811a631'
down_revision = 'fcbc32ac6fdd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 