"""add feedback to user_answers

Revision ID: a863541dccfa
Revises: f4429176445c
Create Date: 2025-07-02 16:25:30.354827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a863541dccfa'
down_revision = 'f4429176445c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_answers', sa.Column('feedback', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_answers', 'feedback')
    # ### end Alembic commands ### 