"""add_resourse_to_questions

Revision ID: ee54cd9b40c4
Revises: 152999a3e9da
Create Date: 2026-05-28 19:42:50.945634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee54cd9b40c4'
down_revision = '152999a3e9da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('resourse', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'resourse')
    # ### end Alembic commands ### 