"""add_user_answers_table

Revision ID: f4429176445c
Revises: a34532f21c47
Create Date: 2025-06-29 01:41:23.711742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4429176445c'
down_revision = 'a34532f21c47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 