"""add optional difficulty field to topics

Revision ID: fcbc32ac6fdd
Revises: 1d95652f9f96
Create Date: 2025-06-28 23:47:35.608804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcbc32ac6fdd'
down_revision = '1d95652f9f96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Создаем enum-тип с правильными значениями
    op.execute("CREATE TYPE difficultyenum AS ENUM ('Легко', 'Средне', 'Сложно')")
    # Добавляем колонку с созданным enum-типом
    op.add_column('topics', sa.Column('difficulty', sa.Enum('Легко', 'Средне', 'Сложно', name='difficultyenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'difficulty')
    op.execute("DROP TYPE difficultyenum")
    # ### end Alembic commands ### 