FROM python:3.11-slim
WORKDIR /app
COPY src/ ./src/
COPY requirements.txt ./requirements.txt
COPY alembic.ini ./alembic.ini
COPY alembic/ ./alembic/
COPY .env ./.env
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt
EXPOSE 8000
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"] 